### PR TITLE
update dependencies, fix tests, add badges

### PR DESCRIPTION
**Pull request by derhuerst**
This PR brings stream-filter up to date.

### CODE REVIEW

**Comment by derhuerst** [comment]
bump.

**Comment by parshap** [comment]
Thanks! This looks great. Do you think a major version bump is needed or is a minor bump sufficient?

**Comment by derhuerst** [comment]
At first, it seems to be backwards-compatible, so, according to [semver](http://semver.org/), it would be a minor change or a bugfix.

However, I don't know if Streams2 (which `through2` uses) are backwards-compatible to Streams1 (which `through` uses). The [Streams2 announcement says however, that Streams2 indeed behave differently if you treat them like Streams1 streams](https://nodejs.org/en/blog/feature/streams2/).

Therefore, I propose a major version bump.

**Comment by parshap** [comment]
Published as `stream-filter@2.0.0` to be safe. Thanks!

**Pull request merged**
